/* QueryLoader v2 */
(function($){$.queryLoader2=function(el,options){var base=this;base.$el=$(el);base.el=el;base.$el.data("queryLoader2",base);base.qLimageContainer="";base.qLoverlay="";base.qLbar="";base.qLpercentage="";base.qLimages=[];base.qLbgimages=[];base.qLimageCounter=0;base.qLdone=0;base.qLdestroyed=false;base.init=function(){base.options=$.extend({},$.queryLoader2.defaultOptions,options);base.findImageInElement(base.el);if(base.options.deepSearch==true)base.$el.find("*:not(script)").each(function(){base.findImageInElement(this)});
base.createPreloadContainer();base.createOverlayLoader()};base.createPreloadContainer=function(){base.qLimageContainer=$("<div></div>").appendTo("body").css({display:"none",width:0,height:0,overflow:"hidden"});for(var i=0;base.qLbgimages.length>i;i++)$.ajax({url:base.qLbgimages[i],type:"HEAD",complete:function(data){if(!base.qLdestroyed)base.addImageForPreload(this["url"])}})};base.addImageForPreload=function(url){var image=$("<img />").attr("src",url);base.bindLoadEvent(image);image.appendTo(base.qLimageContainer)};
base.createOverlayLoader=function(){var overlayPosition="absolute";if(base.$el.prop("tagName")=="BODY")overlayPosition="fixed";else base.$el.css("position","relative");base.qLoverlay=$("<div id='"+base.options.overlayId+"'></div>").css({width:"100%",height:"100%",backgroundColor:base.options.backgroundColor,backgroundPosition:"fixed",position:overlayPosition,zIndex:666999,top:0,left:0}).appendTo(base.$el);base.qLbar=$("<div id='qLbar'></div>").css({height:base.options.barHeight+"px",marginTop:"-"+
base.options.barHeight/2+"px",backgroundColor:base.options.barColor,width:"0%",position:"absolute",top:"50%"}).appendTo(base.qLoverlay);if(base.options.percentage==true)base.qLpercentage=$("<div id='qLpercentage'></div>").text("0%").css({height:"40px",width:"100px",position:"absolute",fontSize:"3em",top:"50%",left:"50%",marginTop:"-"+(59+base.options.barHeight)+"px",textAlign:"center",marginLeft:"-50px",color:base.options.barColor}).appendTo(base.qLoverlay);if(!base.qLimages.length)base.destroyContainers()};
base.destroyContainers=function(){base.qLdestroyed=true;base.qLimageContainer.remove();base.qLoverlay.remove()};base.findImageInElement=function(element){var url="";var obj=$(element);var type="normal";if(obj.css("background-image")!="none"){url=obj.css("background-image");type="background"}else if(typeof obj.attr("src")!="undefined"&&element.nodeName.toLowerCase()=="img")url=obj.attr("src");if(url.indexOf("gradient")==-1){url=url.replace(/url\(\"/g,"");url=url.replace(/url\(/g,"");url=url.replace(/\"\)/g,
"");url=url.replace(/\)/g,"");var urls=url.split(", ");for(var i=0;i<urls.length;i++)if(urls[i].length>0&&(base.qLimages.indexOf(urls[i])==-1&&!urls[i].match(/^(data:)/i))){var extra="";if(base.isIE()||base.isOpera()){extra="?rand="+Math.random();base.qLbgimages.push(urls[i]+extra)}else if(type=="background")base.qLbgimages.push(urls[i]);else base.bindLoadEvent(obj);base.qLimages.push(urls[i])}}};base.isIE=function(){return navigator.userAgent.match(/msie/i)};base.isOpera=function(){return navigator.userAgent.match(/Opera/i)};
base.bindLoadEvent=function(element){base.qLimageCounter++;element.bind("load error",function(){base.completeImageLoading(this)})};base.completeImageLoading=function(el){base.qLdone++;var percentage=base.qLdone/base.qLimageCounter*100;base.qLbar.stop().animate({width:percentage+"%",minWidth:percentage+"%"},200);if(base.options.percentage==true)base.qLpercentage.text(Math.ceil(percentage)+"%");if(base.qLdone==base.qLimageCounter)base.endLoader()};base.endLoader=function(){base.qLdestroyed=true;base.onLoadComplete()};
base.onLoadComplete=function(){if(base.options.completeAnimation=="grow"){var animationTime=500;base.qLbar.stop().animate({"width":"100%"},animationTime,function(){$(this).animate({top:"0%",width:"100%",height:"100%"},500,function(){$("#"+base.options.overlayId).fadeOut(500,function(){$(this).remove();base.destroyContainers();base.options.onComplete()})})})}else $("#"+base.options.overlayId).fadeOut(500,function(){$("#"+base.options.overlayId).remove();base.destroyContainers();base.options.onComplete()})};
base.init()};$.queryLoader2.defaultOptions={onComplete:function(){},backgroundColor:"#000",barColor:"#fff",overlayId:"qLoverlay",barHeight:1,percentage:false,deepSearch:true,completeAnimation:"fade",minimumTime:500};$.fn.queryLoader2=function(options){return this.each(function(){new $.queryLoader2(this,options)})}})(jQuery);
if(!Array.prototype.indexOf)Array.prototype.indexOf=function(elt){var len=this.length>>>0;var from=Number(arguments[1])||0;from=from<0?Math.ceil(from):Math.floor(from);if(from<0)from+=len;for(;from<len;from++)if(from in this&&this[from]===elt)return from;return-1};